#coordinate: coordinate.cpp 
#	g++ -o coordinate coordinate.cpp -I/usr/include/python2.7 -lpython2.7
#	./coordinate

pattern: pattern_generation.cpp
	g++ -o pattern_generation pattern_generation.cpp -I/usr/include/python2.7 -lpython2.7
